title: IBM Data Science Elite
description: Accelerating Data Science and Machine Learning adoption
site_logo: /images/IBM-DSE.gif
github_username:  IBM-DSE

url: "http://ibm-dse.github.io"
permalink: /:categories/:title

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
